trigger:
- cicd-dev

pool:
  vmImage: 'ubuntu-latest'

steps:
#Exporting the module version from module.json for Docker Image Module versioning
- script: |
    echo '##vso[task.setvariable variable=moduleversion]'$(jq -r .image.tag.version $(System.DefaultWorkingDirectory)/modules/serialportmodule/module.json)

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: jantielens

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'modules/SerialPortModule/Dockerfile.amd64'
    buildContext: 'modules/SerialPortModule/'
    containerRegistry: 'jantielens'
    repository: 'jantielens/serialportmodule'
    tags: '$(moduleversion)-amd64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo apt update && sudo apt install qemu-user-static -y'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo cp /usr/bin/qemu-arm-static $(System.DefaultWorkingDirectory)/modules/SerialPortModule/'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'modules/SerialPortModule/Dockerfile.arm32v7'
    buildContext: 'modules/SerialPortModule/'
    containerRegistry: 'jantielens'
    repository: 'jantielens/serialportmodule'
    tags: '$(moduleversion)-arm32v7'